name: Deploy
on:
  workflow_dispatch
permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    environment: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile') }}
          restore-keys: ${{ runner.os }}-gem-

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle

      - uses: rubygems/release-gem@v1
